#!/usr/bin/env python
#===============================================================================
#===============================================================================
# Test driver for wndo
#
# Sets up for testing wndo in-place in the build environment.
#
# Author Steve Cooper   steve@wijjo.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#===============================================================================

import sys
import os.path

dirTest = os.path.split(os.path.abspath(sys.argv[0]))[0]
dirLib  = os.path.join(dirTest, 'lib')
dirTestCmdoD = os.path.join(dirTest, 'cmdo.d')
dirTestWndoD = os.path.join(dirTest, 'wndo.d')

pathSys = sys.path
sys.path.insert(0, dirLib)
import wndo
sys.path = pathSys
import cmdo.public
sys.path = pathSys

# Just look here for .cmdo modules
cmdo.public.engine.dirsScript  = [dirTestCmdoD]
cmdo.public.program.dirsScript = [dirTestWndoD]

if __name__ == '__main__':
    wndo.main('TEST')
