#!/usr/bin/env python
#===============================================================================
#===============================================================================
# Documentation generator for wndo
#
# A wndo frontend script designed to run as part of build to generate
# documentation.
#
# Author Steve Cooper   steve@wijjo.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#===============================================================================

import sys
import os.path
import glob

dirSelf = os.path.split(os.path.abspath(sys.argv[0]))[0]

# Go up until a populated wndo.d directory is found
# Needed to make debian package build work because .cmdo files are not present
# in the temporary tree when this is invoked to generate documentation.
dirScripts = os.path.join(os.path.split(dirSelf)[0], 'wndo.d')
if not glob.glob(os.path.join(dirScripts, '*.cmdo*')):
    dirScripts = os.path.join(os.path.split(os.path.split(dirSelf)[0])[0], 'wndo.d')

import cmdo

# Just look here for .cmdo modules
cmdo.public.program.dirsScript = [dirScripts]

if __name__ == '__main__':
    cmdo.main('DOCGEN')
